import turtle
t = turtle.Turtle()
screen = turtle.Screen()
screen.bgcolor("black")
t.speed(1)
t.color("red")
t.hideturtle()
t.setheading(90)
t.begin_fill()
t.fillcolor("red")
for i in range(2):
    t.forward(80)
    t.circle(-10,90)
    t.fd(120)
    t.circle(-10,90)
t.end_fill()
t.up()
t.goto(50,15)
t.down()
t.color("white")
t.begin_fill()
t.fillcolor("white")
for i in range(3):
    t.fd(50)
    t.right(120)
t.end_fill()
turtle.done()